---
# tasks file for ansible_sshkeys
- name: setting up {{ username110 }} .ssh directory
  file:
    path: "/home/{{ username110 }}/.ssh"
    mode: "0700"
    owner: "{{ username110 }}"
    group: "{{ username110 }}"
    state: directory

- name: generate rsa ssh key pair for user {{ username110 }}
  openssh_keypair:
    path: "/home/{{ username110 }}/.ssh/id_rsa"
    owner: "{{ username110 }}"
    group: "{{ username110 }}"

